### ISSUE TITLE
I don't know how to change character name to character id

### ISSUE THREAD

**Issue by a-club113** [DEViantUA/EnkaNetworkCard#15]
I'm very sorry I'm new to Python, so I don't know how to change character name to character id.
how can I do it?

**Comment by DEViantUA** [comment]
Specify the question or problem, where to replace, why replace?

**Comment by a-club113** [comment]
I'm using [this code](https://github.com/DEViantUA/EnkaCard?tab=readme-ov-file#launch) with `save=True`, but this code creates all characters card.
But i want to create only one character. I don't know the character's id

**Comment by DEViantUA** [comment]
character_id = "id_character, id_character, ..."

1205 - Blade Character ID

``` py

from enkacard import encbanner
import asyncio

async def card():
    async with encbanner.ENC(uid = "811455610", character_id = "1205", save = True) as encard:
        return await encard.creat()

result = asyncio.run(card()) 

print(result)

```

**Comment by a-club113** [comment]
hmm...

alright, thanks
