### ISSUE TITLE
Doesn't Add up?

### ISSUE THREAD

**Issue by ShresthVaibhav** [DEViantUA/EnkaNetworkCard#5]
![image](https://user-images.githubusercontent.com/105759853/217816707-3f850972-bb07-426e-b05d-dafa7e529a37.png)

**Comment by GauravM512** [comment]
latest pypi version
![card](https://user-images.githubusercontent.com/37218716/217840954-bc87c94b-c3e1-4568-988d-c41f14018c6c.png)

**Comment by ShresthVaibhav** [comment]
well i am using 

"https://web-production-32d8.up.railway.app/api/card"

to get images link .... so i dont think pypi would have effect

**Comment by ShresthVaibhav** [comment]
> latest pypi version ![card](https://user-images.githubusercontent.com/37218716/217840954-bc87c94b-c3e1-4568-988d-c41f14018c6c.png)

i am not confident in using lib cause i get stuck and it doesnt has examples ......... 
so i am using "https://web-production-32d8.up.railway.app/api/card"

**Comment by DEViantUA** [comment]
Wait, will be updated soon.

**Comment by ShresthVaibhav** [comment]
> Wait, will be updated soon.

ok i will close the issue
