### ISSUE TITLE
CD>CR? 

### ISSUE THREAD

**Issue by ShresthVaibhav** [DEViantUA/EnkaNetworkCard#6]
![photo_2023-02-12_13-56-08](https://user-images.githubusercontent.com/105759853/218301257-433cc846-17af-48a4-9fde-7aa5d47c6673.jpg)

lib:
Crit Rate after crit DMG is it possible to make cards with crit rate being before than Crit dmg

api:
It has same as lib but at theres more like Max hp at 3rd, def at 1st

**Comment by DEViantUA** [comment]
It seems that I updated the API and now there should be a different order.

**Comment by ShresthVaibhav** [comment]
> It seems that I updated the API and now there should be a different order.

Thanks!!!
And what about library?

**Comment by GauravM512** [comment]
it is updated , but u only use the API

**Comment by ShresthVaibhav** [comment]
> it is updated , but u only use the API


Now i don't Now i use Lib method(i feel like i am being trolled)

**Comment by DEViantUA** [comment]
> > Кажется, я обновил API и теперь должен быть другой порядок.
> 
> Спасибо!!! А как же библиотека?

The library has also been updated, check your version.

**Comment by ShresthVaibhav** [comment]
Thanks a bunch
